name: moniepoint
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  animate_do: ^3.3.3
  flutter_floating_bottom_bar: ^1.2.1+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Euclid Circular
      fonts:
        - asset: assets/fonts/Euclid Circular A Bold.ttf
        - asset: assets/fonts/Euclid Circular A Bold Italic.ttf
        - asset: assets/fonts/Euclid Circular A Medium.ttf
        - asset: assets/fonts/Euclid Circular A Medium Italic.ttf
        - asset: assets/fonts/Euclid Circular A Light.ttf
        - asset: assets/fonts/Euclid Circular A Light Italic.ttf
        - asset: assets/fonts/Euclid Circular A Regular.ttf
        - asset: assets/fonts/Euclid Circular A SemiBold.ttf
        - asset: assets/fonts/Euclid Circular A SemiBold Italic.ttf

